version: '3.9'

services:
  nh-health-db:
    image: nh-health-db
    container_name: nh-health-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=nhhealthdb
    volumes:
      - "nhhealthdb-data:/var/lib/postgresql/data"

volumes:
  nhhealthdb-data:  
